[versions]
paper = "1.20.4-R0.1-SNAPSHOT"
commandapi = "9.4.1"
graalvm = "23.1.8" # NOTE: updating this pessmizes perf
junit-jupiter = "5.13.4"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
commandapi-bukkit-core = { module = "dev.jorel:commandapi-bukkit-core", version.ref = "commandapi" }

graalvm-polyglot = { module = "org.graalvm.polyglot:polyglot", version.ref = "graalvm" }
graalvm-python-community = { module = "org.graalvm.polyglot:python-community", version.ref = "graalvm" }
graalvm-truffle-api = { module = "org.graalvm.truffle:truffle-api", version.ref = "graalvm" }
graalvm-truffle-runtime = { module = "org.graalvm.truffle:truffle-runtime", version.ref = "graalvm" }
graalvm-truffle-dsl-processor = { module = "org.graalvm.truffle:truffle-dsl-processor", version.ref = "graalvm" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }